config/routes.rb
WeStutterNYC::Application.routes.draw do

  devise_for :users 

  devise_scope :user do
    get "/login" => "devise/sessions#new"
  end
  
  resources :events

  resources :recaps

  resources :users

  get 'about', to: "info#about"
  get 'contact', to: "info#contact"
  get 'donate', to: "info#donate"
  get 'home', to: "info#home"
  get 'styles', to: "info#styles"
  get 'thank_you', to: "info#thank_you"

  

    root 'info#home'

  

end

app/models/event.rb
class Event < ActiveRecord::Base
	default_scope order('start_datetime ASC')
	self.inheritance_column = nil

	mount_uploader :photo, ImageUploader
end

app/models/recap.rb
class Recap < ActiveRecord::Base
	mount_uploader :photo, ImageUploader

	default_scope order('created_at DESC')

	belongs_to :user

	validates_presence_of :user_id, :title, :body

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	# validates :name, presence: true
	validates :email, presence: true
	validates :email, uniqueness: true

	has_many :recaps


# def active_for_authentication? 
#   super && approved? 
# end 

# def inactive_message 
#   if !approved? 
#     :not_approved 
#   else 
#     super # Use whatever other message 
#   end 
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_devise_permitted_parameters, if: :devise_controller?

  protected

  def require_admin!
    if !current_user.admin 
      redirect_to root_path, alert: "You are not an admin!"
    end
  end

  def configure_devise_permitted_parameters
    registration_params = [:name, :email, :password, :password_confirmation]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) { 
        |u| u.permit(registration_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) { 
        |u| u.permit(registration_params) 
      }
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_filter :require_admin!, only: [:new, :edit, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:start_datetime, :end_datetime, :venue, :address, :cost, :name, :details, :type, :photo)
    end
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

end

app/controllers/recaps_controller.rb
class RecapsController < ApplicationController
  before_action :set_recap, only: [:show, :edit, :update, :destroy]
  before_filter :require_admin!, only: [:new, :edit, :destroy]
  # i think what i did at the top is correct, i added new, and took out index. 

  # GET /recaps
  # GET /recaps.json
  def index
    @recaps = Recap.all
  end

  # GET /recaps/1
  # GET /recaps/1.json
  def show
  end

  # GET /recaps/new
  def new
    @recap = Recap.new
  end

  # GET /recaps/1/edit
  def edit
  end

  # POST /recaps
  # POST /recaps.json
  def create
    @recap = Recap.new(recap_params)

    respond_to do |format|
      if @recap.save
        format.html { redirect_to @recap, notice: 'Recap was successfully created.' }
        format.json { render action: 'show', status: :created, location: @recap }
      else
        format.html { render action: 'new' }
        format.json { render json: @recap.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recaps/1
  # PATCH/PUT /recaps/1.json
  def update
    respond_to do |format|
      if @recap.update(recap_params)
        format.html { redirect_to @recap, notice: 'Recap was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @recap.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recaps/1
  # DELETE /recaps/1.json
  def destroy
    @recap.destroy
    respond_to do |format|
      format.html { redirect_to recaps_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recap
      @recap = Recap.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recap_params
      params.require(:recap).permit(:title, :body, :user_id, :photo)
    end

# def original_url
#   base_url + original_fullpath
# end

    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :require_admin!, only: [:index, :edit, :destroy]

  # GET /users
  # GET /users.json
  def index
    if params[:approved] == "false"
      @users = User.find_all_by_approved(false)
    else
      @users = User.all
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to(:back) }
        flash[:notice] = "You are signed up!"
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { redirect_to(:back) }
        flash[:notice] = "There was a problem"
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :subscribed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def is_admin?
		user_signed_in? && current_user.admin
	end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/recaps_helper.rb
module RecapsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <h4>Enter the start date time below</h4>
    <%= f.datetime_select :start_datetime %>
  </div>

  <div class="field">
  <h4>Enter the end date time below</h4>
    <%= f.datetime_select :end_datetime %>
  </div>

  <div class="field">
  <h4>Enter the location below</h4>
    <%= f.text_field :venue %>
  </div>

  <div class="field">
  <h4>Enter the address below</h4>
    <%= f.text_field :address %>
  </div>

  <div class="field">
  <h4>Enter the cost below</h4>
    <%= f.text_field :cost %>
  </div>

  <div class="field">
   <h4>Enter the name of the event below</h4>
    <%= f.text_field :name %>
  </div>

  <div class="field">
   <h4>Enter the event details below</h4>
    <%#= tinymce %>
    <%= f.text_area :details %>
  </div>

  <div class="field">
   <h4>Enter the type of the event below (Group, Social Event, Baseball game, etc.</h4>
    <%= f.text_field :type %>
  </div>
  <div class="actions">
    <%= f.file_field :photo %>
  </div>
  <div class="actions">
    <%= f.submit class: "button green" %>
  </div>


<% end %>

app/views/events/edit.html.erb
<%= render "info/menu" %>
<%= render 'info/logo_container' %>

<div class="page_wrapper">
		<section class="container">

					<div id="blog" class="page">


<h1>Edit Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>
</div>
		</section>

<%= render "info/footer" %>

app/views/events/index.html.erb
<%= render 'info/menu' %>
  
<%= render 'info/logo_container' %>

  
  <div class="page_wrapper">
    <section class="container">
      
      <!-- Start Event List -->

      <div id="events_list" class="page">
              <% if is_admin? %>
              <p><%= link_to 'New Event', new_event_path %></p>
               <% end %>
  
      <div class="sub_heading">
        <h1>Upcoming Events</h1>
        </div>


        <!-- Start Event Item -->
        <% @events.each do |event| %>

        <div class="list">
          <div class="box_heading">
            <h2> <%= event.start_datetime.strftime("%A, %B %e, %Y @ %l:%M%P") %></h2>
            <span class="line"></span>
          </div>

          <div class="event_details">
            <!-- <h5><%#= event.name %></h5> -->
            <h3><%= link_to event.name, event %></h3>
            <% if is_admin? %> <%= link_to 'Edit Event', edit_event_path(event) %> <%= link_to 'Delete Event', event, method: :delete, data: { confirm: 'Are you sure?' } %> 
            <% end %>

             <div class="managed_content">
               <%= simple_format(event.details) %>
            </div>

          </div>
          <div class="event_date">
            <ul class="left">
              <li>Start:</li>
              <li>End:</li>
              <li>Place:</li>
              <li>Address:</li>
              <li>Cost:</li>
            </ul>
            <ul class="right">
              <li><%=event.start_datetime.strftime("%l:%M%P")%></li>
              <li><%=event.end_datetime.strftime("%l:%M%P")%></li>
              <li><%=event.venue%></li>
              <li><%=event.address%></li>
              <li><%=event.cost%></li>
            </ul>
          </div>
        </div>

        <% end %>
        <!-- End Event Item -->

        
       
          
      </div>
        
    </section>
  </div>
    
      <%= render 'info/footer' %>

app/views/events/new.html.erb
<%= render "info/menu" %>
<%= render 'info/logo_container' %>

<div class="page_wrapper">
		<section class="container">
			
			<!-- Start Page Content -->
			<div id="blog" class="page">

			<h1>New event</h1>

<%= render 'form' %>
				<div class="actions">
				<%= link_to 'Back', events_path, class: "button pink" %>

			</div>
</div>
		</section>

<%= render "info/footer" %>

app/views/events/show.html.erb
<%= render "info/menu" %>

<%= render "info/logo_container" %>
      
      <!-- Start Social Icons -->
      
      <!-- End Social Icons -->
 
  
<div class="page_wrapper">
    <section class="container">
                              <!-- Start Event List -->
    <div id="events" class="page">
        <h1> <%= @event.name %></h1>  

        <% if is_admin? %>
        <%= link_to 'Edit Event ', edit_event_path(@event) %> 
        <%= link_to 'Delete Event', @event, method: :delete, data: { confirm: 'Are you sure?' } %> 
        <% end %>
        <!-- Start Event Item -->
        <div class="event">
            
                  <div class="event_date">
                    <ul class="one">
                          <li>Event:</li>
                          <li>Start:</li>
                          <li>End:</li>
                          <li>Cost:</li>
                          <li>Date:</li>
                    </ul>
                     <ul class="two">
                          <li> <%= @event.name %></li>
                          <li><%=@event.start_datetime.strftime("%l:%M %P")%> </li>
                          <li><%=@event.end_datetime.strftime("%l:%M %P")%></li>
                          <li><%= @event.cost %></li>
                          <li><%= @event.start_datetime.strftime("%B %e, %Y")  %></li>
                     </ul>
                      <ul class="three">
                          <li>Place:</li>
                          <li>Address:</li>
                     </ul>
                      <ul class="four">
                          <li> <%= @event.venue %></li>
                          <li> <%= @event.address %></li>
                     </ul> 
                  </div>

                  <div class="managed_content">
                   <%= simple_format(@event.details) %>
                 </div>
                          <!-- End Event Item -->   
         </div>
     </div>
         <p class="back_to_recaps"> <%= link_to "back to events", events_path %></p>
  </section>
</div> 

 <%#= image_tag @event.photo, class: "rounded recap_photos" if @event.photo %>  

  <%= render "info/footer" %>

  

  




<!-- the above code will not be here when site is up -->

app/views/info/_address.html.erb
<p>
	119 W. 40th Street <br/>
	14th Floor <br/>
	New York, NY 10018
</p>

app/views/info/_contact_info.html.erb
<p>
							119 W. 40th Street <br/>
							14th Floor <br/>
							New York, NY 10018
						</p>

app/views/info/_logo_container.html.erb
<section class="page_heading">
		<div class="logo container">
			<a href="">NSA Midtown Manhattan Chapter</a>			
			<span class="tagline">if you stutter, you are not alone</span>
		</div>
	</section>

app/views/info/_menu.html.erb
<header>
		<div class="container">		
			<!-- Start Navigation -->
			<nav>
				<ul>
					<li><%= link_to "home", root_path %></li>
					<li><%= link_to "about", about_path %></li>
					<li><%= link_to "recaps", recaps_path %></li>
					<li><%= link_to "events", events_path %></li>



					<!-- <li><a href="events_list.html">events</a></li> -->
					<!-- <li><%#= link_to "gallery", gallery_2_columns_sidebar_path %> -->

						<!-- <a href="#">gallery</a> -->
					<!-- 	<ul>
							<li><a href="gallery_2_columns.html">Gallery 2 Columns</a></li>
							<li><a href="gallery_3_columns.html">Gallery 3 Columns</a></li>
							<li><a href="gallery_4_columns.html">Gallery 4 Columns</a></li>
							<li>
								<a href="#">Gallery With Sidebar &rarr;</a>
								<ul>
									<li><a href="gallery_2_columns_sidebar.html">2 Columns With Sidebar</a></li>
									<li><a href="gallery_3_columns_sidebar.html">3 Columns With Sidebar</a></li>
									<li><a href="gallery_4_columns_sidebar.html">4 Columns With Sidebar</a></li>
								</ul>
							</li>
						</ul>
					</li> -->

					<!-- <li><%#= link_to "donate", donate_path %></li> -->

					<li><%= link_to "contact", contact_path %></li>

					<% if user_signed_in? %>
					<li><%= link_to "log out", destroy_user_session_path, method: :delete %></li>
					<% end %> 

					<!-- took out the sign-in form	 -->
					<%# if current_page?(root_url) %>
						<!-- <li><a href="https://docs.google.com/forms/d/1FCpV6BH7vHvgsAG9jWVYxPrd7ZGZRqnB3gb5iQguIgk/viewform" class="button pink">Meeting Sign-In Form</a><li> -->
					<%# end %>


				</ul>
			</nav>
			<!-- End Navigation -->
			
			<!-- Start Social Icons -->
			<aside>
				<ul class="social icon">
					<li><a href="https://twitter.com/westutter" class="twitter-follow-button" title="Twitter">a</a></li>
					<li><a href="https://www.facebook.com/NSAMidtownManhattanChapter" title="Facebook">v</a></li>
					
					<!-- <li> <a href="JavaScript:newPopup('http://www.quackit.com/html/html_help.cfm');">Open a popup window</a></li> -->

	
					

					<!-- i want twitter to open up a new window, like the line below does -->

				

					<!-- <li><a href="" title="Flickr">d</a></li> -->
					<!-- <li><a href="" title="Vimeo">c</a></li> -->
					<!-- <li><a href="" title="Google">t</a></li> -->
					<!-- <li><a href="" title="RSS">b</a></li> -->
					<!-- More Social Icons:
					<li><a href="" title="Picasa">e</a></li>
					<li><a href="" title="dribbble">f</a></li>
					<li><a href="" title="Forrst">g</a></li>
					<li><a href="" title="deviantART">h</a></li>
					<li><a href="" title="WordPress">i</a></li>
					<li><a href="" title="Blogger">j</a></li>
					<li><a href="" title="Yahoo!">k</a></li>
					<li><a href="" title="Amazon">l</a></li>
					<li><a href="" title="LinkedIn">m</a></li>
					<li><a href="" title="Last.fm">n</a></li>
					<li><a href="" title="StumbleUpon">o</a></li>
					<li><a href="" class="Pinterest">p</a></li>
					<li><a href="" title="Xing">q</a></li>
					<li><a href="" title="SoundCloud">r</a></li>
					<li><a href="" title="Delicious">s</a></li>
					<li><a href="" title="Mail">u</a></li>
					<li><a href="" title="Google">w</a></li>
					-->
				</ul>
			</aside>
			<!-- End Social Icons -->
		</div>		
	</header>

app/views/info/thank_you.html.erb
<%= render 'menu' %>
	
<%= render 'logo_container' %>

	
	<div class="page_wrapper">
		<section class="container">
			
			<!-- Start Event List -->
			<div id="events_list" class="page">

				<div class="sub_heading">
					<h2>Thank you for signing up for our newsletter!</h2>
					<span class="line"></span>
				</div>
				
				
				
				
				
					
			</div>
				
		</section>
	</div>
		
			<%= render 'footer' %>

app/views/recaps/_form.html.erb
<%= form_for(@recap, :html => { :multipart => true }) do |f| %>
  <% if @recap.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recap.errors.count, "error") %> prohibited this recap from being saved:</h2>

      <ul>
      <% @recap.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <h4>enter the month below and then recap, ie: July Recap</h4>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <h4>Enter the body below</h4>
    <%= f.label :body %><br>
    <%#= text_area_tag :editor, "", :class => "tinymce", :rows => 40, :cols => 120 %>
    
    <%= f.text_area :body %>
  </div>

  <div class="field">
    <%= f.file_field :photo %>
  </div>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.collection_select :user_id, User.all, :id, :name, {include_blank: true} %>
  </div>

  <div class="actions">
    <%= f.submit class: "button green" %>
  </div>
<% end %>

app/views/recaps/edit.html.erb
<%= render "info/menu" %>
<%= render 'info/logo_container' %>

<div class="page_wrapper">
		<section class="container">
			
			<!-- Start Page Content -->
			<div id="blog" class="page">
<h1>Edit recap</h1>

<%= render 'form' %>

<%= link_to 'Show', @recap %> |
<%= link_to 'Back', recaps_path %>
			</div>
		</section>

<%= render "info/footer" %>

app/views/recaps/index.html.erb
<%= render "info/menu" %>

<%= render 'info/logo_container' %>

  
  <div class="page_wrapper">
    <section class="container">
      
      <!-- Start Page Content -->
      <div id="blog" class="page">
      
        <% if is_admin? %>
        <p><%= link_to 'Add New Recap', new_recap_path %></p>
        <% end %>

        <div class="sub_heading">
          <h1>Monthly Recaps</h1>
          <!-- <span class="line"></span> it would be cool to add a line, but the line crosses over text when font size increases-->
        </div>

      
        
        <% @recaps.each do |recap| %>
        <!-- Start Blog Post -->
        <div class="post">


          <h3><%= link_to recap.title, recap %></h3>  <% if is_admin? %> <%= link_to 'Edit Recap', edit_recap_path(recap) %> <%= link_to 'Delete Recap', recap, method: :delete, data: { confirm: 'Are you sure?' } %> <% end %>



          <div class="meta">
            <span class="date"> <span class="icon general">i</span><%= recap.created_at.strftime("%B %e, %Y") %></span>
            <!-- <span class="comments"><span class="icon social_misc">w</span> <a href="" title="">2 Comments</a></span>   -->
            <span class="author"> <span class="icon social_misc">x</span> <%= User.find(recap.user_id).name %></span>
          </div>
                    <%= image_tag recap.photo, class: "rounded", class:"smaller_recap_img" if recap.photo %>

                    <p> <%= raw truncate(recap.body, length: 500, separator: ' ') { link_to 'read more', recap} %> </p> 


        </div>
        <!-- End Blog Post -->
        <% end %>
       
      </div>
      <!-- End Page Content -->
      
      <!-- Start Sidebar -->
     <%#= render "info/side_bar" %>
      <!-- End Sidebar -->
      
</div>
  <!-- End Blog -->
  
    <%= render "info/footer" %>

app/views/recaps/new.html.erb
<%= render "info/menu" %>
<%= render 'info/logo_container' %>


<div class="page_wrapper">
		<section class="container">
			
			<!-- Start Page Content -->
			<div id="blog" class="page">
				<h1>New recap</h1>



				<%= render 'form' %>

				<div class="actions">
					<%= link_to 'Back', recaps_path, class: "button pink" %>
				</div>
			</div>
		</section>

<%= render "info/footer" %>

app/views/recaps/show.html.erb
<!-- the above code will not be here when site is up -->


<%= render "info/menu" %>

<%= render 'info/logo_container' %>

<div class="page_wrapper">
		<section class="container">
			
			<!-- Start Page Content -->
			<div id="blog" class="page">
				

				<h1> <%= @recap.title %> </h1>
				
				<!-- I'm trying to use the following method .each so I can add the edit/destroy links here -->
				<% if is_admin? %>
				<%= link_to 'Edit Recap', edit_recap_path(@recap) %> 
				<%= link_to 'Delete Recap', @recap, method: :delete, data: { confirm: 'Are you sure?' } %> 
				<% end %>
				
				
				<!-- Start Blog Post -->
				<div class="post">
					
					<!-- <h3> <%= @recap.title %>  </h3> -->
					<div class="meta">
						<span class="date"> <span class="icon general">i</span><%= @recap.created_at.strftime("%B %e, %Y")  %></span>
						<!-- <span class="comments"><span class="icon social_misc">w</span> <a href="" title="">2 Comments</a></span>   -->
						<span class="author"> <span class="icon social_misc">x</span> by <%= User.find(@recap.user_id).name %> </span>

					</div>
				
					<%#= image_tag @recap.photo, class: "rounded recap_photos" if @recap.photo %>
					<div class="managed_content">
					<%= simple_format(@recap.body) %>

					</div>
					<p class="back_to_recaps"><%= link_to "back to all recaps", recaps_path %> </p>

				</div>

				</div>

				<div class="fb-comments" data-href="<%= request.original_url %>" data-mobile="false" data-width="1000" data-numposts="5" data-colorscheme="light"></div>
			

			
			<!-- End Page Content -->
			
			<%#= render "info/side_bar" %>
		
		</section>
	</div>

	<%= render "info/footer" %>







<!-- End Blog Post -->
				
				<!-- Start Comments -->
				<!-- <div id="comments">
					<h4>Comments</h4>

					<ol>
							<li id="comment-1">
								<img alt="" src="http://0.gravatar.com/avatar/ad516503a11cd5ca435acc9bb6523536?s=60" class="avatar avatar-60 photo avatar-default" height="60" width="60">		
								<div class="comment">
									<h5><a href="http://wordpress.org/" rel="external nofollow" class="url">Mr WordPress</a></h5>
									<span class="date">June 17, 2012 at 8:53 pm</span>
									<p>Hi, this is a comment.<br>To delete a comment, just log in and view the post's comments. There you will have the option to edit or delete them.</p>
									<a class="comment-reply-link" href="">Reply</a>		
								</div>
							</li>
					</ol>

					<div id="respond">
						<form action="http://themes.two2twelve.com/wordpress/advocate/wp-comments-post.php" method="post" id="commentform">
							<p class="comment-notes">Your email address will not be published. Required fields are marked <span class="required">*</span></p>							
							<p class="comment-form-author">
								<label for="author">Name</label> <span class="required">*</span>
								<input id="author" name="author" type="text" value="" size="30" aria-required="true">
							</p>
							<p class="comment-form-email">
								<label for="email">Email</label> <span class="required">*</span>
								<input id="email" name="email" type="text" value="" size="30" aria-required="true">
							</p>
							<p class="comment-form-url">
								<label for="url">Website</label>
								<input id="url" name="url" type="text" value="" size="30">
							</p>
							<p class="comment-form-comment">
								<label for="comment">Comment</label>
								<textarea id="comment" name="comment" cols="45" rows="8" aria-required="true"></textarea>
							</p>												
							<p class="form-submit">
								<input name="submit" type="submit" id="submit" value="Post Comment" class="button white">
							</p>
						</form>
					</div>
				</div> -->
				<!-- End Comments -->

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Subscribed</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>


  <%= link_to "All Users", :action => "index" %>

 <%= link_to "Users awaiting approval", :action => "index", :approved => "false" %>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.subscribed %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Subscribed:</strong>
  <%= @user.subscribed %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>